# Generated by Django 4.1.2 on 2023-12-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcateogry_assign',
            name='ta_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.taskassign'),
        ),
    ]
