# Generated by Django 4.1.2 on 2023-11-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogress',
            name='wp_from_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='wp_to_date',
            field=models.DateField(null=True),
        ),
    ]
