# Generated by Django 4.1.2 on 2023-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0002_employeeleave_leave_request_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdetails',
            name='tad_verified_target',
            field=models.IntegerField(default=0),
        ),
    ]
