# Generated by Django 4.1.2 on 2023-11-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0002_workprogress_wp_from_date_workprogress_wp_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workprogress',
            name='wp_workAssignId',
        ),
    ]
