# Generated by Django 4.1.2 on 2023-11-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0004_workassign_wa_target_workassign_wa_target_achived'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='lead_taskAssignId',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.taskassign'),
        ),
    ]
