# Generated by Django 4.1.2 on 2023-11-23 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Registration_Login', '0001_initial'),
        ('DM_Head', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatFormsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add_date', models.DateField(auto_now_add=True, null=True)),
                ('platform_name', models.CharField(default='', max_length=150)),
                ('platform_dataCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('platform_Name', models.CharField(default='', max_length=150)),
                ('platform_TotalCount', models.IntegerField(default=0)),
                ('company_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='DataBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genarated_date', models.DateField(auto_now_add=True, null=True)),
                ('used_count', models.IntegerField(default=0)),
                ('lead_allocate_status', models.IntegerField(default=0)),
                ('allocated_date', models.DateField(null=True)),
                ('lead_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads')),
            ],
        ),
    ]
