# Generated by Django 4.1.2 on 2023-12-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DM_Head', '0001_initial'),
        ('Registration_Login', '0002_businessregister_details_company_identify_id'),
        ('DataManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(default='', max_length=150)),
                ('company_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
            ],
        ),
        migrations.CreateModel(
            name='FollowupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_date', models.DateField(null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('final_status', models.CharField(default='', max_length=150)),
                ('hr_telecaller_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('hs_comp_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
                ('hs_lead_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads')),
            ],
        ),
        migrations.CreateModel(
            name='FollowupDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateField(auto_now_add=True, null=True)),
                ('response', models.TextField(blank=True, default='', null=True)),
                ('nextfollowup_date', models.DateField(null=True)),
                ('response_status', models.CharField(default='', max_length=150)),
                ('comp_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.businessregister_details')),
                ('hr_telecaller_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration_Login.employeeregister_details')),
                ('lead_Id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='DM_Head.leads')),
            ],
        ),
    ]
