# Generated by Django 4.1.2 on 2023-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_Login', '0012_alter_employeeregister_details_emp_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='designationregister_details',
            name='dashboard_id',
            field=models.IntegerField(default=0),
        ),
    ]
